eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8083
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: feign
feign:
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 6000
        readTimeout: 1200000
  hystrix:
    enabled: false

